
[[constraint]]
  name = "github.com/decred/dcrd"
  revision = "008e80bf8668544de4200a08927e95e5926439a0"

[[constraint]]
  name = "github.com/decred/dcrwallet"
  revision = "0027db2f7a9fcce036af661938ff5a35727547a9"

[[constraint]]
  name = "github.com/docker/docker"
  version = "17.03.2-ce"

[[constraint]]
  branch = "master"
  name = "github.com/marcopeereboom/go-homedir"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
