
[[constraint]]
  name = "github.com/decred/dcrd"
  version = "release-v1.3.0-rc1"

[[constraint]]
  name = "github.com/decred/dcrwallet"
  branch = "release-v1.3"

[[constraint]]
  name = "github.com/moby/moby"
  version = "17.03.2-ce"

[[constraint]]
  branch = "master"
  name = "github.com/marcopeereboom/go-homedir"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
